# Generated by Django 5.1.6 on 2025-03-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida_alta', 'Salida de alto valor'), ('orden_no_actualizada', 'Orden sin actualización'), ('solicitud_no_actualizada', 'Solicitud sin actualización'), ('stock_bajo', 'Producto con stock bajo')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('origen_id', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
