# Generated by Django 5.1.6 on 2025-03-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_ordenescompras_mercaderia_puesta_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.solicitud')),
            ],
        ),
    ]
