# Generated by Django 5.1.6 on 2025-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_solicituddetalle_stock_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
