# Generated by Django 5.1.6 on 2025-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_equipo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('camioneta', 'Camioneta'), ('camion', 'Camión'), ('extraccion', 'Extracción'), ('batea', 'Batea'), ('otros', 'Otros')], max_length=20)),
                ('patente', models.CharField(max_length=20)),
            ],
        ),
    ]
