# Generated by Django 5.1.6 on 2025-03-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
        ('ordenes', '0005_solicituddetalle_stock_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.ordenescompras'),
        ),
    ]
